# Generated by Django 2.2.26 on 2022-09-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='psswod2',
            new_name='password2',
        ),
    ]
