# Generated by Django 4.1.2 on 2022-10-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_animal_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=100)),
                ('Farmer_Image', models.ImageField(upload_to='media/farmers')),
            ],
        ),
        migrations.AlterField(
            model_name='treatment',
            name='disease_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
