# Generated by Django 4.1.2 on 2022-10-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_describe_treatment_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Product_name', models.CharField(max_length=50)),
                ('Product_Image', models.ImageField(blank=True, upload_to='')),
                ('location', models.CharField(choices=[('budalangi', 'Budalangi'), ('bulemia', 'Bulemia'), ('port_victoria', 'PortVictoria'), ('busia', 'Busia'), ('igigo', 'Igigo'), ('sirimba', 'Sirimba')], default='budalangi', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.AlterField(
            model_name='farmers',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
    ]
