# Generated by Django 4.1.2 on 2022-10-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_products_delete_animal_alter_farmers_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=50)),
                ('Farmer_Image', models.ImageField(upload_to='media/farmers')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=12)),
                ('Product_name', models.CharField(max_length=50)),
                ('Product_Image', models.ImageField(blank=True, upload_to='')),
                ('location', models.CharField(choices=[('budalangi', 'Budalangi'), ('bulemia', 'Bulemia'), ('port_victoria', 'PortVictoria'), ('busia', 'Busia'), ('igigo', 'Igigo'), ('sirimba', 'Sirimba')], default='Budalangi', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Farmers',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
