# Generated by Django 4.1.2 on 2022-10-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
