# Generated by Django 4.1.2 on 2022-10-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_product_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='location',
            field=models.CharField(choices=[('Budalangi', 'Budalangi'), ('Bulemia', 'Bulemia'), ('Port_victoria', 'PortVictoria'), ('Busia', 'Busia'), ('Igigo', 'Igigo'), ('Sirimba', 'Sirimba')], default='Budalangi', max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
