# Generated by Django 4.1.2 on 2022-11-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_clients_rename_farmer_farmers_delete_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='location',
            field=models.CharField(choices=[('Budalangi', 'Budalangi'), ('Bulemia', 'Bulemia'), ('Port_victoria', 'PortVictoria'), ('Busia', 'Busia'), ('Kisumu', 'Kisumu'), ('Rongo', 'Rongo'), ('Migori', 'Migori'), ('Igigo', 'Igigo'), ('Sirimba', 'Sirimba')], default='Budalangi', max_length=20),
        ),
    ]
