# Generated by Django 4.1.3 on 2022-11-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_products_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='First_name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Last_name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Username',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='phone_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='phone_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='phone_no',
            field=models.PositiveIntegerField(),
        ),
    ]
