# Generated by Django 4.1.3 on 2022-11-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_type_medicines_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicines',
            old_name='name',
            new_name='name_of_medicine_used',
        ),
    ]
