# Generated by Django 4.1.3 on 2022-11-14 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_name_medicines_name_of_medicine_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='Username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='farmers',
            old_name='Username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Username',
            new_name='username',
        ),
    ]
