# Generated by Django 4.1.3 on 2022-11-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_email_clients_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='client',
        ),
    ]
