# Generated by Django 3.2.12 on 2023-02-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_clients_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('farm_no', models.PositiveIntegerField()),
                ('location', models.CharField(choices=[('Budalangi', 'Budalangi'), ('Bulemia', 'Bulemia'), ('Port_victoria', 'PortVictoria'), ('Busia', 'Busia'), ('Mubbwayo', 'Mubwayo'), ('Rongo', 'Rongo'), ('Mundika', 'Mundika'), ('Igigo', 'Igigo'), ('Sirimba', 'Sirimba')], default='Budalangi', max_length=20)),
                ('farm_image', models.ImageField(upload_to='media/')),
            ],
            options={
                'verbose_name_plural': 'Plants',
            },
        ),
        migrations.AlterField(
            model_name='farmers',
            name='Email',
            field=models.EmailField(max_length=12),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='username',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='Description',
            field=models.TextField(max_length=100),
        ),
    ]
