# Generated by Django 4.1.7 on 2023-03-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_quantity_medicines_quantity_in_ml_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicines',
            old_name='name_of_medicine_used',
            new_name='drug_used',
        ),
        migrations.RenameField(
            model_name='medicines',
            old_name='quantity_in_ml',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='medicines',
            old_name='type_of_drug',
            new_name='type',
        ),
    ]
