# Generated by Django 4.1.7 on 2023-03-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_name_of_medicine_used_medicines_drug_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='quantity',
            field=models.CharField(default='ml1', max_length=15),
        ),
        migrations.AlterField(
            model_name='plants',
            name='farm_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plants',
            name='location',
            field=models.CharField(choices=[('Budalangi', 'Budalangi'), ('Bulemia', 'Bulemia'), ('Port_victoria', 'PortVictoria'), ('Busia', 'Busia'), ('Mubwayo', 'Mubwayo'), ('Rongo', 'Rongo'), ('Mundika', 'Mundika'), ('Igigo', 'Igigo'), ('Sirimba', 'Sirimba')], default='Budalangi', max_length=20),
        ),
    ]
