# Generated by Django 3.2.19 on 2024-04-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_medicines_quantity_alter_plants_farm_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='drug_used',
            field=models.CharField(default='Pentagon', max_length=15),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='quantity',
            field=models.CharField(default='1  ml', max_length=15),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='type',
            field=models.CharField(default='Insecticide', max_length=10),
        ),
    ]
