# Generated by Django 3.2.19 on 2024-05-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20240426_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='farm_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_name',
            field=models.CharField(max_length=20),
        ),
    ]
