# Generated by Django 3.2.19 on 2024-05-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20240501_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farmers',
        ),
    ]
